# fly.toml app configuration file generated for tictactoe-lively-tree-8220 on 2024-09-20T11:42:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tictactoe-lively-tree-8220'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
